name: betterban
version: '${version}'
main: top.ymsblog.betterban.Betterban
api-version: '1.20'
author: "yms@ymsblog.top"

commands:
  bban:
    description: "BetterBan"
    permission: betterban.all

permissions:
  betterban.all:
    description: "允许你使用betterban的功能"
    default: true


  betterban.command.reload:
    description: "允许你重载betterban配置"
    default: op

  betterban.donotban:
    description: "允许你不受betterban封禁限制"
    default: op

